dist: bionic

language: python

sudo: required

notifications:
  email: false

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ppa'
    packages:
      - python-dev
      - python3-dev
      - libgdal-dev
      - python-gdal
      - python3-gdal
      - gdal-bin
      - build-essential
      - libssl-dev
      - libffi-dev

python:
  - '3.6'

branches:
  only:
    - master
    - dev

virtualenv:
  system_site_packages: true

install:
  - pip install --ignore-installed "numpy>=1.16" cython
  - pip install .

script:
  - python setup.py test
