os: linux
dist: bionic

language: python

notifications:
  email: false

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ppa'
    packages:
      - python-dev
      - python3-dev
      - libgdal-dev
      - python-gdal
      - python3-gdal
      - gdal-bin
      - build-essential
      - libssl-dev
      - libffi-dev

env:
  - LC_ALL=C.UTF-8
  - LANG=C.UTF-8

python:
  - '3.6'
  - '3.7'
  - '3.8'

branches:
  only:
    - master
    - dev

install:
  - pip install --ignore-installed "numpy>=1.16" cython
  - pip install .

script:
  - python setup.py test
