[tool.poetry]
name = "modape"
version = "1.0.3"
description = "Poetry-compatible version of WFP-VAM Modape"
authors = ["Riccardo D'Ercole"]
readme = "README.rst"

[build-system]
build-backend = 'setuptools.build_meta'
requires = [
    'setuptools >= 43.0.0',
    'numpy  >= 1.16.1',
]
