[tool.poetry]
name = "modape"
version = "1.0.3"
description = ""
authors = [""]
readme = "README.rst"

packages = [
    {include = "_version"},

[build-system]
build-backend = 'setuptools.build_meta'
requires = [
    'setuptools >= 43.0.0',
    'numpy  >= 1.16.1',
]
