name: docs
on:
  push:
    branches:
      - dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install numpy mkdocs-material mkdocstrings
      - run: pip install --no-deps $GITHUB_WORKSPACE
      - run: mkdocs gh-deploy --force
