name: ci
on:
  push:
    branches:
      - gdal3
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: sudo add-apt-repository ppa:ubuntugis/ppa
      - run: sudo apt-get update && sudo apt-get install -y gdal-bin python3-gdal libpq-dev
      - run: pip install cython numpy
      - run: pip install $GITHUB_WORKSPACE
      - run: pip $GITHUB_WORKSPACE/setup.py test
