name: publish

on:
  push:
    branches:
      - workflows

jobs:
  build_wheels:
    name: Build wheels on ubuntu-18.04
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      # Used to host cibuildwheel
      - uses: actions/setup-python@v2

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==1.10.0

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BEFORE_BUILD: "pip install cython numpy"
          CIBW_BUILD: "{cp,pp}3*-*"
          CIBW_SKIP: "cp35-* *-manylinux_i686"

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl